[package]
name = "advinha"
version = "0.1.0"
edition = "2021"
authors = ["Marcelo-maga <marcelo.maga2550@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.3.14"
